### ISSUE TITLE
Animacja buttonu sprawia, że tekst na przycisku drży

### ISSUE THREAD

**Issue by mrypel** [kspacja/herosi-issues#2]
System: Windows
rozdz: 1366x768
Przeglądarka: Chrome

![image](https://github.com/kspacja/herosi-issues/assets/141902759/01598d8d-b533-499e-b35c-0bae97932ca4)

**Comment by kspacja** [comment]
https://github.com/kspacja/herosi/commit/03f29d3615671e0e1525ff0fb3ef06ba117134fd
