### ISSUE TITLE
Nie mam możliwości przesuwania kafelków karuzeli 

### ISSUE THREAD

**Issue by mrypel** [kspacja/herosi-issues#3]
Windows
1366x768
Google Chrome

![image](https://github.com/kspacja/herosi-issues/assets/141902759/0c4b4e36-ebe3-4dc2-b29d-d64b9f8aa6a8)

**Comment by kspacja** [comment]
https://github.com/kspacja/herosi/commit/90c0ed8820fc054b7496a298d99756eecec210ad
